export const SET_CONFIG = 'setConfig'
export const SET_TOKEN = 'setToken'
export const SET_USER = 'setUser'
export const PERMISSIONS = 'permissions'
export const LOGOUT = 'logout'
export const BREADCRUMB = ''
